# -----------------------------------------------------------------------------
# Responsive WebP Images
# -----------------------------------------------------------------------------

# MAKE SURE imagemagick is installed and on your PATH before enabling imagemagick. In a terminal, run:
#   convert -version
imagemagick:
  enabled: false # disables responsive images - use lazy loading instead
